### ISSUE TITLE
对话时发生错误

### ISSUE THREAD

**Issue by xiazhenyz** [InternLM/OpenAOE#62]
我在mac电脑上通过pip的方式安装了openaoe，对话时发生了如下错误
<img width="952" alt="image" src="https://github.com/InternLM/OpenAOE/assets/22024498/d3ae8963-fbd7-49e8-a303-0a9b2363163a">
后台显示的错误
<img width="975" alt="image" src="https://github.com/InternLM/OpenAOE/assets/22024498/6fa6a375-a7e1-4749-9f39-df8a708d933b">

我调用的是config是repo里给的examples：
python3.9 -m openaoe.main -f openaoe/backend/config/config-template.yaml

后台完整输出如下：
INFO:     2024-02-28 10:09:03,800 - biz_config-init_config-line:60 - your config file is: openaoe/backend/config/config-template.yaml
INFO:your config file is: openaoe/backend/config/config-template.yaml
INFO:     2024-02-28 10:09:03,800 - biz_config-load_config-line:65 - start to init configuration from openaoe/backend/config/config-template.yaml.
INFO:start to init configuration from openaoe/backend/config/config-template.yaml.
INFO:     2024-02-28 10:09:03,828 - biz_config-load_config-line:78 - init configuration successfully.
INFO:init configuration successfully.
INFO:     Uvicorn running on http://0.0.0.0:10099 (Press CTRL+C to quit)
INFO:     Started parent process [36986]
INFO:     2024-02-28 10:09:04,857 - biz_config-init_config-line:60 - your config file is: openaoe/backend/config/config-template.yaml
INFO:your config file is: openaoe/backend/config/config-template.yaml
INFO:     2024-02-28 10:09:04,857 - biz_config-load_config-line:65 - start to init configuration from openaoe/backend/config/config-template.yaml.
INFO:start to init configuration from openaoe/backend/config/config-template.yaml.
INFO:     2024-02-28 10:09:04,858 - biz_config-init_config-line:60 - your config file is: openaoe/backend/config/config-template.yaml
INFO:your config file is: openaoe/backend/config/config-template.yaml
INFO:     2024-02-28 10:09:04,858 - biz_config-load_config-line:65 - start to init configuration from openaoe/backend/config/config-template.yaml.
INFO:start to init configuration from openaoe/backend/config/config-template.yaml.
INFO:     2024-02-28 10:09:04,860 - biz_config-init_config-line:60 - your config file is: openaoe/backend/config/config-template.yaml
INFO:your config file is: openaoe/backend/config/config-template.yaml
INFO:     2024-02-28 10:09:04,861 - biz_config-load_config-line:65 - start to init configuration from openaoe/backend/config/config-template.yaml.
INFO:start to init configuration from openaoe/backend/config/config-template.yaml.
INFO:     2024-02-28 10:09:04,867 - biz_config-load_config-line:78 - init configuration successfully.
INFO:init configuration successfully.
INFO:     2024-02-28 10:09:04,868 - biz_config-load_config-line:78 - init configuration successfully.
INFO:init configuration successfully.
INFO:     2024-02-28 10:09:04,869 - biz_config-load_config-line:78 - init configuration successfully.
INFO:init configuration successfully.
INFO:     2024-02-28 10:09:04,906 - biz_config-init_config-line:60 - your config file is: openaoe/backend/config/config-template.yaml
INFO:     2024-02-28 10:09:04,906 - biz_config-init_config-line:60 - your config file is: openaoe/backend/config/config-template.yaml
INFO:your config file is: openaoe/backend/config/config-template.yaml
INFO:your config file is: openaoe/backend/config/config-template.yaml
INFO:     2024-02-28 10:09:04,906 - biz_config-init_config-line:60 - your config file is: openaoe/backend/config/config-template.yaml
INFO:your config file is: openaoe/backend/config/config-template.yaml
INFO:     2024-02-28 10:09:04,906 - biz_config-load_config-line:65 - start to init configuration from openaoe/backend/config/config-template.yaml.
INFO:     2024-02-28 10:09:04,906 - biz_config-load_config-line:65 - start to init configuration from openaoe/backend/config/config-template.yaml.
INFO:start to init configuration from openaoe/backend/config/config-template.yaml.
INFO:start to init configuration from openaoe/backend/config/config-template.yaml.
INFO:     2024-02-28 10:09:04,906 - biz_config-load_config-line:65 - start to init configuration from openaoe/backend/config/config-template.yaml.
INFO:start to init configuration from openaoe/backend/config/config-template.yaml.
INFO:     2024-02-28 10:09:04,915 - biz_config-load_config-line:78 - init configuration successfully.
INFO:     2024-02-28 10:09:04,915 - biz_config-load_config-line:78 - init configuration successfully.
INFO:init configuration successfully.
INFO:init configuration successfully.
INFO:     2024-02-28 10:09:04,917 - biz_config-load_config-line:78 - init configuration successfully.
INFO:init configuration successfully.
INFO:     Started server process [37013]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Started server process [37012]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Started server process [37011]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:61209 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:61209 - "GET /assets/vendor-bad6aacb.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:61210 - "GET /assets/index-d5c224e8.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:61215 - "GET /assets/index-3b28341a.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:61209 - "GET /config/json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61209 - "GET /assets/AOE-b98456c3.svg HTTP/1.1" 200 OK
INFO:     127.0.0.1:61209 - "GET /assets/send-5bb2204f.png HTTP/1.1" 200 OK
INFO:     127.0.0.1:61267 - "POST /v1/minimax/v1/text/chat-stream HTTP/1.1" 200 OK
DEBUG:Starting new HTTPS connection (1): api.minimax.chat:443
DEBUG:https://api.minimax.chat:443 "POST /v1/text/chatcompletion?GroupId=None HTTP/1.1" 200 144
ERROR:     2024-02-28 10:11:11,669 - service_minimax-event_generator_json-line:123 - 'choices'
ERROR:'choices'
所以不知道是哪里配置错误吗？

**Comment by fly2tomato** [comment]
看着像是没有配置`config-template.yaml`。
`openaoe/backend/config/config-template.yaml` 是一个配置的模板，需要你在这个配置文件里设定好你访问大模型API的鉴权信息，比如aksk之类的。

It looks like you use the default `config-template.yaml` without adding any necessary data like API's access key/secret, ect. 
Tell me wrong if the config file is right.
